require 'active_support/all'
require 'sinatra'
require 'sinatra/contrib/all'
require_relative 'Cfg'
require_relative 'Task'
require_relative 'Sinatra'
require_relative 'Bitmex'
require_relative 'Loop'